# Generated by Django 4.2 on 2023-04-28 16:45

from django.db import migrations, models
import i_18n_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("i_18n_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.JSONField(
                default=dict,
                encoder=i_18n_app.models.CustomJSONEncoder,
                verbose_name="Article Title",
            ),
        ),
    ]
